ClientEvents.lang('en_us', e => {
  e.renameItem('justdirethings:ferricore_helmet', 'Ferricore Spacesuit Helmet')
  e.renameItem('justdirethings:ferricore_chestplate', 'Ferricore Spacesuit Chestplate')
  e.renameItem('justdirethings:ferricore_leggings', 'Ferricore Spacesuit Leggings')
  e.renameItem('justdirethings:ferricore_boots', 'Ferricore Spacesuit Boots')
  e.renameItem('justdirethings:blazegold_helmet', 'Blazegold Spacesuit Helmet')
  e.renameItem('justdirethings:blazegold_chestplate', 'Blazegold Spacesuit Chestplate')
  e.renameItem('justdirethings:blazegold_leggings', 'Blazegold Spacesuit Leggings')
  e.renameItem('justdirethings:blazegold_boots', 'Blazegold Spacesuit Boots')
  e.renameItem('justdirethings:celestigem_helmet', 'Celestigem Spacesuit Helmet')
  e.renameItem('justdirethings:celestigem_chestplate', 'Celestigem Spacesuit Chestplate')
  e.renameItem('justdirethings:celestigem_leggings', 'Celestigem Spacesuit Leggings')
  e.renameItem('justdirethings:celestigem_boots', 'Celestigem Spacesuit Boots')
  e.renameItem('justdirethings:eclipsealloy_helmet', 'Eclipse Alloy Spacesuit Helmet')
  e.renameItem('justdirethings:eclipsealloy_chestplate', 'Eclipse Alloy Spacesuit Chestplate')
  e.renameItem('justdirethings:eclipsealloy_leggings', 'Eclipse Alloy Spacesuit Leggings')
  e.renameItem('justdirethings:eclipsealloy_boots', 'Eclipse Alloy Spacesuit Boots')
})
